
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felix
 */
public class student_grades extends javax.swing.JFrame {

    /**
     * Creates new form stud_grades
     */
    public student_grades() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fulln = new javax.swing.JTextField();
        pny = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();
        q6 = new javax.swing.JTextField();
        q7 = new javax.swing.JTextField();
        q8 = new javax.swing.JTextField();
        q9 = new javax.swing.JTextField();
        q10 = new javax.swing.JTextField();
        recitation = new javax.swing.JTextField();
        assignment = new javax.swing.JTextField();
        attendance = new javax.swing.JTextField();
        semestral = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        avequiz = new javax.swing.JTextField();
        aveass = new javax.swing.JTextField();
        semexam = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        finalgrade = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grades");
        setMinimumSize(new java.awt.Dimension(897, 841));
        setPreferredSize(new java.awt.Dimension(897, 841));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(897, 841));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(897, 841));
        jPanel1.setLayout(null);

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(12, 13, 41, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/patts.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(550, 10, 310, 350);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(550, 380, 98, 30);
        jPanel1.add(studid);
        studid.setBounds(650, 380, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(780, 380, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 422, 90, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Year & Program:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 472, 140, 40);
        jPanel1.add(fulln);
        fulln.setBounds(640, 430, 210, 30);
        jPanel1.add(pny);
        pny.setBounds(690, 480, 160, 30);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(510, 0, 390, 550);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 510, 2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 170, 20, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 108, 510, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EXAM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 460, 100, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 200, 20, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 230, 20, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("5.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 260, 20, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("6.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(330, 140, 20, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("7.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(330, 170, 20, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("8.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(330, 200, 20, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("9.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(330, 230, 20, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Semestral Exam:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 690, 140, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("1.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(70, 140, 20, 20);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 310, 510, 2);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("QUIZ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(210, 50, 90, 60);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(0, 370, 510, 2);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("10.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(320, 260, 30, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Recitation:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 390, 90, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Assignment:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(200, 390, 110, 20);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(0, 460, 510, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ASSESSMENT TASK");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(100, 310, 320, 60);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(0, 510, 510, 10);

        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(-10, 548, 920, 2);

        q1.setToolTipText("");
        jPanel1.add(q1);
        q1.setBounds(90, 140, 70, 22);
        jPanel1.add(q2);
        q2.setBounds(90, 170, 70, 22);
        jPanel1.add(q3);
        q3.setBounds(90, 200, 70, 22);
        jPanel1.add(q4);
        q4.setBounds(90, 230, 70, 22);
        jPanel1.add(q5);
        q5.setBounds(90, 260, 70, 22);
        jPanel1.add(q6);
        q6.setBounds(350, 140, 70, 22);
        jPanel1.add(q7);
        q7.setBounds(350, 170, 70, 22);
        jPanel1.add(q8);
        q8.setBounds(350, 200, 70, 22);
        jPanel1.add(q9);
        q9.setBounds(350, 230, 70, 22);
        jPanel1.add(q10);
        q10.setBounds(350, 260, 70, 22);
        jPanel1.add(recitation);
        recitation.setBounds(30, 420, 90, 22);

        assignment.setToolTipText("");
        assignment.setName(""); // NOI18N
        jPanel1.add(assignment);
        assignment.setBounds(200, 420, 100, 22);
        assignment.getAccessibleContext().setAccessibleName("");

        jPanel1.add(attendance);
        attendance.setBounds(370, 420, 100, 22);
        jPanel1.add(semestral);
        semestral.setBounds(260, 520, 110, 22);

        jLabel21.setBackground(new java.awt.Color(255, 242, 0));
        jLabel21.setForeground(new java.awt.Color(255, 242, 0));
        jLabel21.setText("40%");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(480, 480, 30, 30);

        jLabel22.setBackground(new java.awt.Color(255, 242, 0));
        jLabel22.setForeground(new java.awt.Color(255, 242, 0));
        jLabel22.setText("30%");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(480, 80, 30, 30);

        jLabel23.setBackground(new java.awt.Color(255, 242, 0));
        jLabel23.setForeground(new java.awt.Color(255, 242, 0));
        jLabel23.setText("30%");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(480, 340, 30, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Attendance:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(370, 390, 110, 20);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 50, 510, 60);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Semestral Exam:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(120, 520, 140, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Average Quiz:");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(20, 590, 110, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Average Assessment Task:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(20, 640, 210, 30);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(0, 742, 900, 10);

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(690, 750, 100, 30);

        avequiz.setToolTipText("");
        jPanel1.add(avequiz);
        avequiz.setBounds(140, 590, 70, 30);
        jPanel1.add(aveass);
        aveass.setBounds(240, 640, 70, 30);
        jPanel1.add(semexam);
        semexam.setBounds(160, 690, 70, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("FINAL GRADE:");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(450, 630, 240, 50);

        finalgrade.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        finalgrade.setForeground(new java.awt.Color(255, 242, 0));
        jPanel1.add(finalgrade);
        finalgrade.setBounds(690, 620, 210, 70);

        jButton5.setText("Compute");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(690, 690, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try
        {
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/prelim_cg", "root", "");

           int student_id = Integer.parseInt(studid.getText());
           Statement stm = conn.createStatement();
           String sqlsearch = ("SELECT * FROM student_information WHERE student_id='"+student_id+"'");
           ResultSet rs = stm.executeQuery(sqlsearch);
           
           if(rs.next()){
               fulln.setText(rs.getString("student_full_name"));
               pny.setText(rs.getString("student_year_program"));
               q1.setText(rs.getString(String.valueOf("student_quiz1")));
               q2.setText(rs.getString(String.valueOf("student_quiz2")));
               q3.setText(rs.getString(String.valueOf("student_quiz3")));
               q4.setText(rs.getString(String.valueOf("student_quiz4")));
               q5.setText(rs.getString(String.valueOf("student_quiz5")));
               q6.setText(rs.getString(String.valueOf("student_quiz6")));
               q7.setText(rs.getString(String.valueOf("student_quiz7")));
               q8.setText(rs.getString(String.valueOf("student_quiz8")));
               q9.setText(rs.getString(String.valueOf("student_quiz9")));
               q10.setText(rs.getString(String.valueOf("student_quiz10")));
               recitation.setText(rs.getString(String.valueOf("student_recitation")));
               assignment.setText(rs.getString(String.valueOf("student_assignment")));
               attendance.setText(rs.getString(String.valueOf("student_attendance")));
               semestral.setText(rs.getString(String.valueOf("student_semestral_exam")));
               avequiz.setText(rs.getString(String.valueOf("student_ave_quiz")));
               aveass.setText(rs.getString(String.valueOf("student_ave_assessment_task")));
               semexam.setText(rs.getString(String.valueOf("student_ave_exam")));
               finalgrade.setText(rs.getString("student_final_grade"));
               
           }
           
           
        conn.close();
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }                                 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/prelim_cg", "root", "");
           
        int student_id = Integer.parseInt(studid.getText());
        String stud_fn = fulln.getText();
        String py = pny.getText();
        int qz1 = Integer.parseInt(q1.getText());
        int qz2 = Integer.parseInt(q2.getText());
        int qz3 = Integer.parseInt(q3.getText());
        int qz4 = Integer.parseInt(q4.getText());
        int qz5 = Integer.parseInt(q5.getText());
        int qz6 = Integer.parseInt(q6.getText());
        int qz7 = Integer.parseInt(q7.getText());
        int qz8 = Integer.parseInt(q8.getText());
        int qz9 = Integer.parseInt(q9.getText());
        int qz10 = Integer.parseInt(q10.getText());
        int recit = Integer.parseInt(recitation.getText());
        int ass = Integer.parseInt(assignment.getText());
        int att = Integer.parseInt(attendance.getText());
        int sem = Integer.parseInt(semestral.getText());
        float avequizs = Float.parseFloat(avequiz.getText());
        float aveat = Float.parseFloat(aveass.getText());
        float aveexam = Float.parseFloat(semexam.getText());
        float fngrade = Float.parseFloat(finalgrade.getText());

           
           Statement stm = conn.createStatement();
           String sqlUpdate = ("UPDATE student_information SET student_id='"+student_id+"',student_full_name='"+stud_fn+"',student_year_program='"+py+"',student_quiz1='"+qz1+"',"
           + "student_quiz2='"+qz2+"',student_quiz3='"+qz3+"',student_quiz4='"+qz4+"',student_quiz5='"+qz5+"',student_quiz6='"+qz6+"',student_quiz7='"+qz7+"',student_quiz8='"+qz8+"',"
                   + "student_quiz9='"+qz9+"',student_quiz10='"+qz10+"',student_recitation='"+recit+"',student_assignment='"+ass+"',student_attendance='"+att+"',"
                   + "student_semestral_exam='"+sem+"',student_ave_quiz='"+avequizs+"',student_ave_assessment_task='"+aveat+"',student_ave_exam='"+aveexam+"',student_final_grade='"+fngrade+"' WHERE student_id='"+student_id+"'");
           stm.execute(sqlUpdate);
           
        conn.close();
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int qz1 = Integer.parseInt(q1.getText());
        int qz2 = Integer.parseInt(q2.getText());
        int qz3 = Integer.parseInt(q3.getText());
        int qz4 = Integer.parseInt(q4.getText());
        int qz5 = Integer.parseInt(q5.getText());
        int qz6 = Integer.parseInt(q6.getText());
        int qz7 = Integer.parseInt(q7.getText());
        int qz8 = Integer.parseInt(q8.getText());
        int qz9 = Integer.parseInt(q9.getText());
        int qz10 = Integer.parseInt(q10.getText());
        
        float qzs = (qz1+qz2+qz3+qz4+qz5+qz6+qz7+qz8+qz9+qz10);
        float aveqzs = (float) (qzs * .30);
        avequiz.setText(String.valueOf(aveqzs));
        
        int recit = Integer.parseInt(recitation.getText());
        int ass = Integer.parseInt(assignment.getText());
        int att = Integer.parseInt(attendance.getText());
        
        float atasks = (recit+ass+att);
        float aveatasks = (float) (atasks * 0.3);
        aveass.setText(String.valueOf(aveatasks));
        
        int sem = Integer.parseInt(semestral.getText());
        float avexam = (float) (sem * 0.4);
        semexam.setText(String.valueOf(avexam));
        
        float final_grade = aveqzs + aveatasks + avexam ;
        finalgrade.setText(String.valueOf(final_grade));
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_grades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assignment;
    private javax.swing.JTextField attendance;
    private javax.swing.JTextField aveass;
    private javax.swing.JTextField avequiz;
    private javax.swing.JLabel finalgrade;
    private javax.swing.JTextField fulln;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField pny;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q10;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    private javax.swing.JTextField q6;
    private javax.swing.JTextField q7;
    private javax.swing.JTextField q8;
    private javax.swing.JTextField q9;
    private javax.swing.JTextField recitation;
    private javax.swing.JTextField semestral;
    private javax.swing.JTextField semexam;
    private javax.swing.JTextField studid;
    // End of variables declaration//GEN-END:variables
}
